---

backup_command:
  eos: show run
  ios: show run
  nxos: show run
  junos: show configuration
connection_details:
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  host: "{{ inventory_hostname }}"