---

  - name: Build Configuration Files
    hosts: eos-leaves
    gather_facts: no
    connection: local

    tasks:
      - name: BUILD CONFIGS
        template: src=templates/eos-leaf.j2 dest=configs/{{inventory_hostname }}.conf

      - name: PUSH CONFIGS
        napalm_install_config:
          hostname={{ inventory_hostname }}
          username={{ ansible_user }}
          password={{ ansible_ssh_pass }}
          dev_os={{ ansible_network_os }}
          config_file=configs/{{ inventory_hostname }}.conf
          diff_file=diffs/{{ inventory_hostname }}.diffs
          commit_changes=true
          replace_config=false
        tags: push