---
- name: COLLECT USERNAME AND PASSWORD
  hosts: csr1
  gather_facts: no

  vars_prompt:
    - name: un
      prompt: "Please enter the username"
      private: no
      
    - name: pwd
      prompt: "Please enter the password"
      private: yes
      
  tasks:

    - name: DISPLAY THE USERNAME AND PASSWORD
      debug:
        msg: "The Username is {{ un }} and password is {{ pwd }}"

